version: 2.1
jobs:
  BuildAndTest:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "securegroups/__init__.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make dev
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pip install -U pip
            pip install tox && tox
      - store_artifacts:
          path: htmlcov/
      - save_cache:
          key: v1-dependency-cache-{{ checksum "securegroups/__init__.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"
            - ".tox"
  Deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "securegroups/__init__.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make dev
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $pypi-api-token" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            make package
      - save_cache:
          key: v1-dependency-cache-{{ checksum "securegroups/__init__.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"
            - ".tox"
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  SecureGroups:
    jobs:
      - BuildAndTest
      - Hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - BuildAndTest
      - Deploy:
          requires:
            - BuildAndTest
            - Hold
